"""Small, idempotent Android adaptations for the pinned DXVK source only.

Fail on source drift rather than silently applying a partial patch. The Vulkan
loader already supports libvulkan.so; SDL still owns Android surface creation.
"""
import pathlib
import sys

root = pathlib.Path(sys.argv[1])
variant = sys.argv[2] if len(sys.argv) > 2 else "v2"


def replace(relative_path, old, new):
    """Apply one required replacement, or fail when the pinned source drifts."""
    path = root / relative_path
    text = path.read_text(encoding="utf-8")
    if new and new in text:
        return
    if text.count(old) != 1:
        raise RuntimeError(
            f"Unexpected pinned DXVK source in {relative_path}: {old!r}")
    path.write_text(text.replace(old, new), encoding="utf-8", newline="\n")


def replace_prefer_old(relative_path, old, new):
    """Replace an old form even when the new form is a substring of it."""
    path = root / relative_path
    text = path.read_text(encoding="utf-8")
    if text.count(old) == 1:
        path.write_text(text.replace(old, new), encoding="utf-8", newline="\n")
        return
    if new and new in text:
        return
    raise RuntimeError(
        f"Unexpected pinned DXVK source in {relative_path}: {old!r}")


def replace_optional(relative_path, old, new):
    """Upgrade a known previous patch form, if it is present."""
    path = root / relative_path
    text = path.read_text(encoding="utf-8")
    if new and new in text:
        return
    if text.count(old) == 1:
        path.write_text(text.replace(old, new), encoding="utf-8", newline="\n")


def remove_optional(relative_path, old):
    """Remove a superseded patch fragment when upgrading an existing cache."""
    path = root / relative_path
    text = path.read_text(encoding="utf-8")
    if old in text:
        path.write_text(text.replace(old, ""), encoding="utf-8", newline="\n")


def normalize_queue_includes(relative_path):
    """Collapse duplicate Android queue includes left by an older patch order."""
    path = root / relative_path
    text = path.read_text(encoding="utf-8")
    start = '#include "dxvk_queue.h"\n'
    end = "namespace dxvk {"
    if start not in text or end not in text:
        return

    begin = text.index(start)
    finish = text.index(end, begin)
    region = text[begin:finish]
    if not any(marker in region for marker in (
            '#include "../vulkan/vulkan_android_timing.h"',
            '#include <SDL_log.h>')):
        return

    # This region is entirely generated by this script. Keep the check strict
    # so a future upstream include is not silently discarded while repairing a
    # cache made by the old overlapping include patches.
    known = (
        start,
        '\n#include "../vulkan/vulkan_android_timing.h"\n',
        '\n#if defined(__ANDROID__)\n#include <cstdlib>\n#include <SDL_log.h>\n#endif\n',
    )
    remainder = region
    for fragment in known:
        remainder = remainder.replace(fragment, "")
    if remainder.strip():
        raise RuntimeError(
            f"Unexpected generated include region in {relative_path}: {region!r}")

    canonical = '''#include "dxvk_queue.h"

#include "../vulkan/vulkan_android_timing.h"

#if defined(__ANDROID__)
#include <cstdlib>
#include <SDL_log.h>
#endif

'''
    path.write_text(
        text[:begin] + canonical + text[finish:],
        encoding="utf-8",
        newline="\n")


def replace_one_of(relative_path, alternatives, new):
    """Replace exactly one known upstream form, or fail on unexpected drift."""
    path = root / relative_path
    text = path.read_text(encoding="utf-8")
    if new and new in text:
        return

    matches = [old for old in alternatives if old in text]
    if len(matches) != 1 or text.count(matches[0]) != 1:
        raise RuntimeError(
            f"Unexpected pinned DXVK source in {relative_path}: "
            f"expected exactly one of {alternatives!r}")
    path.write_text(text.replace(matches[0], new), encoding="utf-8", newline="\n")


def replace_all(relative_path, old, new, expected_count):
    """Replace a known number of repeated upstream forms strictly."""
    path = root / relative_path
    text = path.read_text(encoding="utf-8")
    if new and new in text:
        return
    if text.count(old) != expected_count:
        raise RuntimeError(
            f"Unexpected pinned DXVK source in {relative_path}: {old!r}")
    path.write_text(text.replace(old, new), encoding="utf-8", newline="\n")


def write_if_missing(relative_path, content):
    """Install an Android-only source file without overwriting an existing one."""
    path = root / relative_path
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def patch_v2():
    """Apply the seven minimal Android changes to clean pinned DXVK 2.7.1."""
    # Android packages SDL2 as libSDL2.so rather than a desktop SONAME.
    replace("src/wsi/sdl2/wsi_platform_sdl2.cpp",
            '#elif defined(__APPLE__)',
            '#elif defined(__ANDROID__)\n        "libSDL2.so"\n#elif defined(__APPLE__)')
    # DXVK's SDL2 WSI dynamically resolves symbols, so only the matching app
    # headers are needed at compile time.
    replace("meson_options.txt", "option('enable_dxgi',",
            "option('android_sdl2_include', type: 'string', value: '', description: 'Android SDL2 headers')\noption('enable_dxgi',")
    replace("meson.build",
            "  lib_sdl2 = dependency('sdl2', required: get_option('native_sdl2'))",
            """  if platform == 'android'
    assert(get_option('android_sdl2_include') != '', 'Android SDL2 headers required')
    lib_sdl2 = declare_dependency(compile_args: ['-I' + get_option('android_sdl2_include')])
  else
    lib_sdl2 = dependency('sdl2', required: get_option('native_sdl2'))
  endif""")
    # The resource and shader generators execute on the host during a cross build.
    replace("meson.build", "find_program('touch')",
            "find_program('touch', native: true)")
    replace("meson.build", "find_program('glslang', 'glslangValidator')",
            "find_program('glslang', 'glslangValidator', native: true)")
    # Android uses the app's shared libc++ and unversioned ELF SONAMEs.
    replace("meson.build", """  link_args += [
    '-static-libgcc',
    '-static-libstdc++',
  ]""", """  if platform == 'android'
    dxvk_so_version = {}
  else
    link_args += ['-static-libgcc', '-static-libstdc++']
  endif""")
    # DXVK's monolithic graphics-pipeline fallback does not use this extension.
    # It remains required on desktop, while Android accepts adapters without it.
    replace("src/dxvk/dxvk_device_info.cpp",
            """      /* Dependency for graphics pipeline library */
      ENABLE_EXT(khrPipelineLibrary, true),""",
            """      /* Required only when the optional graphics-pipeline-library path is used. */
#if defined(__ANDROID__)
      ENABLE_EXT(khrPipelineLibrary, false),
#else
      ENABLE_EXT(khrPipelineLibrary, true),
#endif""")


def patch_v1():
    """Patch the legacy DXVK 1.x fork used by the native compatibility path."""
    # The native 1.x fork links SDL2 directly and has no dynamic WSI loader.
    # Android surfaces must use a composite-alpha mode reported by the driver.
    replace("src/vulkan/vulkan_presenter.cpp",
            "    swapInfo.compositeAlpha         = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;",
            """    swapInfo.compositeAlpha = static_cast<VkCompositeAlphaFlagBitsKHR>(
      caps.supportedCompositeAlpha & (~caps.supportedCompositeAlpha + 1u));""")
    # VK_SUBOPTIMAL_KHR is persistent on some Android WSI implementations. Do
    # not recreate the swap chain every frame while presentation is valid.
    replace_one_of("src/d3d9/d3d9_swapchain.cpp", (
            """    if (status != VK_SUCCESS) {
      Logger::info(str::format(
        "D3D9SwapChainEx: present status before recreate: ", status));
      RecreateSwapChain(m_vsync);
    }""",
            "    if (status != VK_SUCCESS)\n      RecreateSwapChain(m_vsync);",
        ),
            """    if (status != VK_SUCCESS && status != VK_SUBOPTIMAL_KHR)
      RecreateSwapChain(m_vsync);""")
    # Mali exposes 16 vertex inputs; omit unused fixed-function blend inputs.
    replace("src/dxvk/dxvk_graphics.cpp",
            "    for (uint32_t i = 0; i < state.il.attributeCount(); i++) {\n      viAttribs[i] = state.ilAttributes[i].description();\n      viAttribs[i].binding = viBindingMap[state.ilAttributes[i].binding()];\n    }",
            """    uint32_t viAttributeCount = 0;
    for (uint32_t i = 0; i < state.il.attributeCount(); i++) {
      if (!(m_shaders.vs->interfaceSlots().inputSlots & (1u << state.ilAttributes[i].location())))
        continue;
      viAttribs[viAttributeCount] = state.ilAttributes[i].description();
      viAttribs[viAttributeCount++].binding = viBindingMap[state.ilAttributes[i].binding()];
    }""")
    replace("src/dxvk/dxvk_graphics.cpp",
            "viInfo.vertexAttributeDescriptionCount  = state.il.attributeCount();",
            "viInfo.vertexAttributeDescriptionCount  = viAttributeCount;")
    replace("src/dxvk/dxvk_graphics.cpp",
            "    uint32_t sampleMask = state.ms.sampleMask();",
            """    rsInfo.depthClampEnable &= m_pipeMgr->m_device->features().core.features.depthClamp;

    uint32_t sampleMask = state.ms.sampleMask();""")
    # Compatible render passes need matching dependencies. Use conservative
    # Android barriers and retain the attachment-sampling self dependency.
    replace("src/dxvk/dxvk_renderpass.cpp",
            "    VkRenderPassCreateInfo info;",
            """#if defined(__ANDROID__)
    subpassDepCount = 3;
    subpassDeps[0] = { VK_SUBPASS_EXTERNAL, 0,
      VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT,
      VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT, 0 };
    subpassDeps[1] = { 0, 0,
      VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
      VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT,
      VK_DEPENDENCY_BY_REGION_BIT };
    subpassDeps[2] = { 0, VK_SUBPASS_EXTERNAL,
      VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
      VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT,
      VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT, 0 };
#endif

    VkRenderPassCreateInfo info;""")
    # ClipDistance is optional on mobile. Do not emit its SPIR-V capability
    # (even for disabled planes) when the Vulkan device cannot support it.
    replace("src/dxso/dxso_options.h", "    bool useDemoteToHelperInvocation = false;",
            "    bool useDemoteToHelperInvocation = false;\n    bool useClipDistance = true;")
    replace("src/dxso/dxso_options.cpp",
            "    const DxvkDeviceFeatures& devFeatures = device->features();",
            "    const DxvkDeviceFeatures& devFeatures = device->features();\n    useClipDistance = devFeatures.core.features.shaderClipDistance;")
    replace("src/dxso/dxso_compiler.cpp",
            "    m_module.enableCapability(spv::CapabilityClipDistance);",
            "    if (m_moduleInfo.options.useClipDistance)\n      m_module.enableCapability(spv::CapabilityClipDistance);")
    replace("src/dxso/dxso_compiler.cpp", "  void DxsoCompiler::emitVsClipping() {",
            "  void DxsoCompiler::emitVsClipping() {\n    if (!m_moduleInfo.options.useClipDistance) return;")
    replace("src/d3d9/d3d9_fixed_function.h",
            "D3D9FixedFunctionOptions(const D3D9Options* options);",
            "D3D9FixedFunctionOptions(D3D9DeviceEx* device);\n    bool useClipDistance;")
    replace("src/d3d9/d3d9_fixed_function.cpp",
            "D3D9FixedFunctionOptions::D3D9FixedFunctionOptions(const D3D9Options* options) {",
            "D3D9FixedFunctionOptions::D3D9FixedFunctionOptions(D3D9DeviceEx* device) {\n    const auto* options = device->GetOptions();\n    useClipDistance = device->GetDXVKDevice()->features().core.features.shaderClipDistance;")
    replace_all("src/d3d9/d3d9_fixed_function.cpp",
                "      pDevice->GetOptions());",
                "      D3D9FixedFunctionOptions(pDevice));", expected_count=2)
    replace("src/d3d9/d3d9_fixed_function.cpp",
            "    m_module.enableCapability(spv::CapabilityClipDistance);",
            "    if (m_options.useClipDistance)\n      m_module.enableCapability(spv::CapabilityClipDistance);")
    replace("src/d3d9/d3d9_fixed_function.cpp",
            "  void D3D9FFShaderCompiler::emitVsClipping(uint32_t vtx) {",
            "  void D3D9FFShaderCompiler::emitVsClipping(uint32_t vtx) {\n    if (!m_options.useClipDistance) return;")
    replace("src/d3d9/d3d9_adapter.cpp",
            "pCaps->MaxUserClipPlanes         = MaxClipPlanes;",
            "pCaps->MaxUserClipPlanes         = m_adapter->features().core.features.shaderClipDistance ? MaxClipPlanes : 0;")
    replace("src/d3d9/d3d9_device.cpp",
            "  HRESULT STDMETHODCALLTYPE D3D9DeviceEx::SetRenderState(D3DRENDERSTATETYPE State, DWORD Value) {",
            """  HRESULT STDMETHODCALLTYPE D3D9DeviceEx::SetRenderState(D3DRENDERSTATETYPE State, DWORD Value) {
    if (State == D3DRS_CLIPPLANEENABLE && Value
     && !m_dxvkDevice->features().core.features.shaderClipDistance) {
      Logger::err("D3D9: User clip planes are unsupported by this Vulkan device");
      return D3DERR_INVALIDCALL;
    }""")
    replace("src/dxvk/dxvk_queue.cpp",
                       '#include "dxvk_queue.h"\n',
                       '''#include "dxvk_queue.h"

#if defined(__ANDROID__)
#include <cstdlib>
#include <SDL_log.h>
#endif
''')
    replace_all("src/dxvk/dxvk_queue.cpp",
                       "        m_device->waitForIdle();",
                       '''#if defined(__ANDROID__)
        if (status == VK_ERROR_DEVICE_LOST) {
          SDL_LogError(SDL_LOG_CATEGORY_RENDER, "DXVK v1: Vulkan device lost in %s", __func__);
          std::_Exit(2);
        }
#endif
        m_device->waitForIdle();''', expected_count=2)
    # Upgrade checkouts that already received the old immediate-exit patch.
    replace("src/dxvk/dxvk_queue.cpp", "#include <cstdlib>\n#endif",
                       "#include <cstdlib>\n#include <SDL_log.h>\n#endif")
    replace("src/dxvk/dxvk_queue.cpp",
                       "#if defined(__ANDROID__)\n        if (status == VK_ERROR_DEVICE_LOST)\n          std::_Exit(2);\n#endif\n", "")
    replace("meson.build", "lib_sdl2    = dependency('SDL2')",
                       "lib_sdl2    = declare_dependency(include_directories: include_directories(get_option('android_sdl2_include')), link_args: ['-L' + get_option('android_sdl2_lib'), '-lSDL2'])" )

    replace("meson.build", "lib_vulkan  = dependency('vulkan')",
            "lib_vulkan  = dxvk_compiler.find_library('vulkan')")
    replace("meson.build", "dxvk_extradep = [ ]",
            """dxvk_extradep = [ ]
lib_swappy = declare_dependency(
  compile_args: ['-I' + get_option('android_swappy_include')],
  link_args: [get_option('android_swappy_lib'), '-landroid', '-llog'])""")
    replace_all("meson.build",
                "lib_vulkan  = dxvk_compiler.find_library('vulkan-1', dirs : dxvk_library_path)",
                "lib_vulkan  = dxvk_compiler.find_library('vulkan')", expected_count=2)

    replace("meson.build", "wrc = find_program('echo')",
                       "wrc = find_program('cmake', native: true)")
    replace("meson.build", "wrc = find_program('cmd.exe', native: true)",
                       "wrc = find_program('cmake', native: true)")
    replace("meson.build", "arguments : [ 'Ignoring: ', '@INPUT@' ]",
                       "arguments : [ '-E', 'touch', '@OUTPUT@' ]")
    replace("meson.build", "arguments : [ '/c', 'echo', 'Ignoring: ', '@INPUT@' ]",
                       "arguments : [ '-E', 'touch', '@OUTPUT@' ]")
    replace("meson.build", "glsl_compiler = find_program('glslangValidator')",
                       "glsl_compiler = find_program('glslang', native: true)")
    replace("src/d3d9/meson.build", "dependencies        : [ dxso_dep, dxvk_dep, wsi_dep ],",
                       "dependencies        : [ dxso_dep, dxvk_dep, wsi_dep, lib_sdl2 ],")
    replace("src/d3d9/meson.build", "vs_module_defs      : 'd3d9'+def_spec_ext,",
                       "vs_module_defs      : 'd3d9'+def_spec_ext,\n  link_args           : ['-L' + get_option('android_sdl2_lib'), '-lSDL2'],")
    replace("src/dxvk/meson.build", "dependencies        : [ thread_dep, vkcommon_dep ] + dxvk_extradep,",
                       "dependencies        : [ thread_dep, vkcommon_dep, lib_sdl2 ] + dxvk_extradep,")
    replace_one_of("src/vulkan/meson.build", (
            "vkcommon_deps = [ thread_dep, wsi_dep, lib_vulkan ]",
            "vkcommon_deps = [ thread_dep, wsi_dep, lib_vulkan, lib_sdl2 ]",
        ),
            "vkcommon_deps = [ thread_dep, wsi_dep, lib_vulkan, lib_sdl2, lib_swappy ]")
    replace("src/vulkan/meson.build",
            """vkcommon_dep = declare_dependency(
  link_with           : [ vkcommon_lib ],
  include_directories : [ dxvk_include_path ])""",
            """vkcommon_dep = declare_dependency(
  link_with           : [ vkcommon_lib ],
  dependencies        : [ lib_swappy ],
  include_directories : [ dxvk_include_path ])""")
    replace("src/dxvk/platform/dxvk_sdl2_exts.cpp",
                       "namespace dxvk {\n\n  DxvkPlatformExts DxvkPlatformExts::s_instance;",
                       "namespace dxvk {\n\n#if defined(__ANDROID__)\n  static SDL_Window* s_androidWindow = nullptr;\n\n  extern \"C\" void dxvkSetSdl2Window(SDL_Window* window) {\n    s_androidWindow = window;\n  }\n#endif\n\n  DxvkPlatformExts DxvkPlatformExts::s_instance;")
    replace("src/dxvk/platform/dxvk_sdl2_exts.cpp",
                       '''    SDL_Window* window = SDL_CreateWindow(
      "Dummy Window",
      SDL_WINDOWPOS_UNDEFINED,
      SDL_WINDOWPOS_UNDEFINED,
      1, 1,
      SDL_WINDOW_HIDDEN | SDL_WINDOW_VULKAN);''',
                       '''    SDL_Window* window = nullptr;
#if defined(__ANDROID__)
    if (s_androidWindow == nullptr)
      throw DxvkError("SDL2 WSI: Application window was not supplied on Android");
    window = s_androidWindow;
#else
    window = SDL_CreateWindow(
      "Dummy Window",
      SDL_WINDOWPOS_UNDEFINED,
      SDL_WINDOWPOS_UNDEFINED,
      1, 1,
      SDL_WINDOW_HIDDEN | SDL_WINDOW_VULKAN);
#endif''')
    replace("src/dxvk/platform/dxvk_sdl2_exts.cpp",
                       "    SDL_DestroyWindow(window);\n\n    return names;",
                       "#if !defined(__ANDROID__)\n    SDL_DestroyWindow(window);\n#endif\n\n    return names;")
    replace("src/d3d9/d3d9_main.cpp",
                       "#include \"../dxvk/dxvk_instance.h\"",
                       "#include <cstdio>\n#include \"../dxvk/dxvk_instance.h\"")
    replace("src/d3d9/d3d9_main.cpp",
                       """    dxvk::CreateD3D9(false, &pDirect3D);

    return pDirect3D;""",
                       """    try {
      dxvk::CreateD3D9(false, &pDirect3D);
    } catch (const dxvk::DxvkError& e) {
      std::fprintf(stderr, \"DXVK v1 Direct3DCreate9: %s\\n\", e.message().c_str());
    } catch (...) {
      std::fprintf(stderr, \"DXVK v1 Direct3DCreate9: unknown native exception\\n\");
    }

    return pDirect3D;""")
    # The fork assumes desktop D3D9 features and enables several Vulkan bits
    # unconditionally. Mobile Vulkan 1.1 drivers may expose valid D3D9 paths
    # without all of them; enable only what the adapter reports.
    for feature in ("depthClamp", "depthBiasClamp", "fillModeNonSolid",
                    "sampleRateShading", "shaderClipDistance",
                    "textureCompressionBC", "multiViewport", "independentBlend"):
        replace("src/d3d9/d3d9_device.cpp",
                           "enabled.core.features.%s = VK_TRUE;" % feature,
                           "enabled.core.features.%s = supported.core.features.%s;" % (feature, feature))
    replace("src/d3d9/d3d9_device.cpp", "DxvkDeviceFeatures enabled = {};",
                       """DxvkDeviceFeatures enabled = {};
    if (!supported.core.features.shaderInt64) Logger::warn(\"Android DXVK v1 missing feature: shaderInt64\");
    if (!supported.core.features.textureCompressionBC) Logger::warn(\"Android DXVK v1 missing feature: textureCompressionBC\");
    if (!supported.core.features.multiDrawIndirect) Logger::warn(\"Android DXVK v1 missing feature: multiDrawIndirect\");
    if (!supported.core.features.multiViewport) Logger::warn(\"Android DXVK v1 missing feature: multiViewport\");
    if (!supported.core.features.shaderClipDistance) Logger::warn(\"Android DXVK v1 missing feature: shaderClipDistance\");
    if (!supported.core.features.shaderCullDistance) Logger::warn(\"Android DXVK v1 missing feature: shaderCullDistance\");""")
    write_if_missing("src/util/platform/util_env_android.cpp", r'''#include "../util_env.h"

#include <cerrno>
#include <filesystem>
#include <string>
#include <sys/prctl.h>
#include <unistd.h>

namespace dxvk::env {

std::string getExePath() {
  char path[4096] = { };
  const ssize_t len = readlink("/proc/self/exe", path, sizeof(path) - 1);
  return len > 0 ? std::string(path, size_t(len)) : std::string();
}

void setThreadName(const std::string& name) {
  std::string truncated = name.substr(0, 15);
  prctl(PR_SET_NAME, truncated.c_str(), 0, 0, 0);
}

bool createDirectory(const std::string& path) {
  std::error_code error;
  std::filesystem::create_directories(path, error);
  return !error;
}

}
''')
    write_if_missing("src/util/platform/util_string_android.cpp", r'''#include "util_string.h"

#include <cstdint>
#include <string>

namespace dxvk::str {

std::string fromws(const WCHAR* ws) {
  if (!ws) return {};
  std::string out;
  for (const uint32_t* p = reinterpret_cast<const uint32_t*>(ws); *p; ++p) {
    uint32_t cp = *p;
    if (cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) cp = 0xfffd;
    if (cp <= 0x7f) out.push_back(char(cp));
    else if (cp <= 0x7ff) { out.push_back(char(0xc0 | (cp >> 6))); out.push_back(char(0x80 | (cp & 63))); }
    else if (cp <= 0xffff) { out.push_back(char(0xe0 | (cp >> 12))); out.push_back(char(0x80 | ((cp >> 6) & 63))); out.push_back(char(0x80 | (cp & 63))); }
    else { out.push_back(char(0xf0 | (cp >> 18))); out.push_back(char(0x80 | ((cp >> 12) & 63))); out.push_back(char(0x80 | ((cp >> 6) & 63))); out.push_back(char(0x80 | (cp & 63))); }
  }
  return out;
}

void tows(const char* mbs, WCHAR* wcs, size_t wcsLen) {
  if (!wcs || !wcsLen) return;
  size_t out = 0;
  const unsigned char* p = reinterpret_cast<const unsigned char*>(mbs ? mbs : "");
  while (*p && out + 1 < wcsLen) {
    const unsigned char lead = *p++;
    int extra = lead < 0x80 ? 0 : lead < 0xe0 ? 1 : lead < 0xf0 ? 2 : 3;
    uint32_t cp = extra == 0 ? lead : extra == 1 ? (lead & 0x1f) : extra == 2 ? (lead & 0x0f) : (lead & 7);
    if (extra && (!*p || (*p & 0xc0) != 0x80)) cp = 0xfffd, extra = 0;
    for (int i = 0; i < extra; ++i) { if ((p[i] & 0xc0) != 0x80) { extra = -1; break; } cp = (cp << 6) | (p[i] & 63); }
    if (extra < 0) { cp = 0xfffd; ++p; } else p += extra;
    wcs[out++] = static_cast<WCHAR>(cp > 0x10ffff ? 0xfffd : cp);
  }
  wcs[out] = 0;
}

}
''')
    write_if_missing("src/util/platform/util_luid_android.cpp", r'''#include "../util_luid.h"

#include "../log/log.h"

namespace dxvk {
LUID GetAdapterLUID(UINT) {
  static bool warned = false;
  if (!warned) { Logger::warn("GetAdapterLUID: Android has no native LUID; using zero"); warned = true; }
  return LUID();
}
}
''')
    replace("src/util/meson.build", "elif dxvk_platform == 'darwin'\n  util_src += util_src_darwin\nelse",
                       "elif dxvk_platform == 'darwin'\n  util_src += util_src_darwin\nelif dxvk_platform == 'android'\n  util_src += ['platform/util_env_android.cpp', 'platform/util_string_android.cpp', 'platform/util_luid_android.cpp', 'platform/thread_native.cpp']\nelse")
    # The old fork has no android_sdl2_include option; add one for the SDL
    # headers supplied by the application and use it in its native dependency.
    replace("meson_options.txt", "option('enable_tests',", "option('android_sdl2_include', type: 'string', value: '')\noption('android_sdl2_lib', type: 'string', value: '')\noption('android_swappy_include', type: 'string', value: '')\noption('android_swappy_lib', type: 'string', value: '')\noption('enable_tests',")


if variant == "v2":
    patch_v2()
elif variant == "native":
    patch_v1()
else:
    raise ValueError(f"Unknown DXVK variant: {variant!r}")
